"""
Pydantic v2 models for the LLM Hallucination Tester service.

Defines request/response schemas used by the FastAPI endpoints and
shared across the hallucination-checking pipeline.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Verdict(str, Enum):
    """Possible hallucination verdicts for a single answer."""

    ACCURATE = "ACCURATE"
    HALLUCINATED = "HALLUCINATED"
    UNCERTAIN = "UNCERTAIN"


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------


class HallucinationRequest(BaseModel):
    """Incoming payload for the POST /check-hallucination endpoint."""

    topic: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="The subject or topic to test for hallucinations.",
        examples=["The Apollo 11 moon landing"],
    )
    num_questions: int = Field(
        default=5,
        ge=1,
        description="Number of factual questions to generate.",
    )
    model: str = Field(
        default="gpt-4o-mini",
        description="OpenAI model identifier to use (e.g. gpt-4o-mini).",
    )
    reference: Optional[str] = Field(
        default=None,
        description="Optional reference/context to verify answers against.",
    )

    @field_validator("topic")
    @classmethod
    def topic_must_not_be_blank(cls, v: str) -> str:
        """Ensure the topic string is not purely whitespace."""
        if not v.strip():
            raise ValueError("topic must not be blank or whitespace only.")
        return v.strip()


# ---------------------------------------------------------------------------
# Intermediate Pipeline Models
# ---------------------------------------------------------------------------


class QuestionAnswer(BaseModel):
    """A single question-answer pair produced by the pipeline."""

    question: str = Field(..., description="The factual question generated by the model.")
    answer: str = Field(
        ..., description="The model's answer to the question — the text being verified."
    )


class QuestionGenerationResult(BaseModel):
    """Structured response from the LLM for Stage 1."""

    questions: List[str] = Field(..., description="List of generated questions.")


class VerificationAssessment(BaseModel):
    """Structured assessment of a QA pair from the LLM for Stage 3."""

    verdict: Verdict = Field(..., description="ACCURATE, HALLUCINATED, or UNCERTAIN verdict.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Heuristic confidence score.")
    reasoning: str = Field(..., description="Brief explanation supporting the verdict.")


class EvaluationSummary(BaseModel):
    """Detailed summary counts and rates for the evaluation."""

    accurate_count: int = Field(..., description="Number of accurate answers.")
    hallucinated_count: int = Field(..., description="Number of hallucinated answers.")
    uncertain_count: int = Field(..., description="Number of uncertain answers.")
    hallucination_rate: float = Field(..., description="Factual hallucination rate.")
    summary_text: str = Field(..., description="Human-readable text summary.")


# ---------------------------------------------------------------------------
# Result / Response Models
# ---------------------------------------------------------------------------


class VerificationResult(BaseModel):
    """Fact-checking result for one question-answer pair."""

    question: str = Field(..., description="The original factual question.")
    answer: str = Field(..., description="The answer that was verified.")
    verdict: Verdict = Field(
        ..., description="ACCURATE, HALLUCINATED, or UNCERTAIN verdict."
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 (none) and 1.0 (certain).",
    )
    reasoning: str = Field(
        ..., description="Brief explanation supporting the verdict."
    )
    # New fields (backward compatible)
    llm_judge_verdict: Optional[Verdict] = Field(
        default=None,
        description="The raw verdict returned by the LLM fact checker before normalization."
    )


class HallucinationResponse(BaseModel):
    """Full response returned by POST /check-hallucination."""

    topic: str = Field(..., description="The topic that was tested.")
    questions_tested: int = Field(
        ..., description="Total number of questions evaluated."
    )
    hallucination_rate: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Fraction of answers scored as HALLUCINATED.",
    )
    results: List[VerificationResult] = Field(
        ..., description="Per-question verification details."
    )
    summary: str = Field(
        ..., description="Human-readable summary of the hallucination analysis."
    )
    
    # New metadata fields (backward compatible)
    analysis_id: str = Field(..., description="Unique UUID for this analysis session.")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp of the analysis.")
    model_used: str = Field(..., description="Model used for the evaluation.")
    evaluation_mode: str = Field(..., description="Evaluation mode: LLM_JUDGE_ONLY or REFERENCE_BASED.")
    
    # Timing fields
    question_generation_latency_ms: float = Field(0.0, description="Stage 1 latency in milliseconds.")
    answer_generation_latency_ms: float = Field(0.0, description="Stage 2 latency in milliseconds.")
    fact_check_latency_ms: float = Field(0.0, description="Stage 3 latency in milliseconds.")
    total_latency_ms: float = Field(0.0, description="Total pipeline latency in milliseconds.")
    
    # Structured summary
    evaluation_summary: Optional[EvaluationSummary] = Field(
        default=None,
        description="Detailed evaluation counts and summary."
    )
    
    # Responsible AI disclaimer
    disclaimer: str = Field(
        default=(
            "This tool provides automated LLM-based factuality assessments and should not be treated as definitive ground truth. "
            "Results may contain errors and should be independently verified for high-stakes use."
        ),
        description="Responsible AI disclaimer."
    )


# ---------------------------------------------------------------------------
# Health-check model
# ---------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Response schema for the GET /health endpoint."""

    status: str = Field(default="ok")
    service: str = Field(default="LLM Hallucination Tester")
    version: str = Field(default="1.0.0")
