"""
Pydantic v2 models for the LLM Hallucination Tester service.

Defines request/response schemas used by the FastAPI endpoints and
shared across the hallucination-checking pipeline.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Verdict(str, Enum):
    """Possible hallucination verdicts for a single answer."""

    ACCURATE = "ACCURATE"
    HALLUCINATED = "HALLUCINATED"
    UNCERTAIN = "UNCERTAIN"


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------


class HallucinationRequest(BaseModel):
    """Incoming payload for the POST /check-hallucination endpoint."""

    topic: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="The subject or topic to test for hallucinations.",
        examples=["The Apollo 11 moon landing"],
    )
    num_questions: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Number of factual questions to generate (1-10).",
    )
    model: str = Field(
        default="gpt-4o-mini",
        description="OpenAI model identifier to use (e.g. gpt-4o-mini).",
    )

    @field_validator("topic")
    @classmethod
    def topic_must_not_be_blank(cls, v: str) -> str:
        """Ensure the topic string is not purely whitespace."""
        if not v.strip():
            raise ValueError("topic must not be blank or whitespace only.")
        return v.strip()


# ---------------------------------------------------------------------------
# Intermediate Pipeline Models
# ---------------------------------------------------------------------------


class QuestionAnswer(BaseModel):
    """A single question-answer pair produced by the pipeline."""

    question: str = Field(..., description="The factual question generated by the model.")
    answer: str = Field(
        ..., description="The model's answer to the question — the text being verified."
    )


# ---------------------------------------------------------------------------
# Result / Response Models
# ---------------------------------------------------------------------------


class VerificationResult(BaseModel):
    """Fact-checking result for one question-answer pair."""

    question: str = Field(..., description="The original factual question.")
    answer: str = Field(..., description="The answer that was verified.")
    verdict: Verdict = Field(
        ..., description="ACCURATE, HALLUCINATED, or UNCERTAIN verdict."
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 (none) and 1.0 (certain).",
    )
    reasoning: str = Field(
        ..., description="Brief explanation supporting the verdict."
    )


class HallucinationResponse(BaseModel):
    """Full response returned by POST /check-hallucination."""

    topic: str = Field(..., description="The topic that was tested.")
    questions_tested: int = Field(
        ..., description="Total number of questions evaluated."
    )
    hallucination_rate: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Fraction of answers scored as HALLUCINATED.",
    )
    results: List[VerificationResult] = Field(
        ..., description="Per-question verification details."
    )
    summary: str = Field(
        ..., description="Human-readable summary of the hallucination analysis."
    )


# ---------------------------------------------------------------------------
# Health-check model
# ---------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Response schema for the GET /health endpoint."""

    status: str = Field(default="ok")
    service: str = Field(default="LLM Hallucination Tester")
    version: str = Field(default="1.0.0")
